apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: activemq
  name: activemq
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: activemq
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: activemq
    spec:
      containers:
        - image: rmohr/activemq:5.15.9-alpine
          name: active
          ports:
            - containerPort: 61616
            - containerPort: 8161
          resources: {}
      restartPolicy: Always
status: {}
