apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: activemq
  name: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: activemq
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: activemq
    spec:
      containers:
        - image: rmohr/activemq:5.15.9-alpine
          name: active
          ports:
            - containerPort: 61616
            - containerPort: 8161
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: angular
  name: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: angular
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: angular
    spec:
      containers:
        - image: pludynia/simple-web-app-frontend:1.6
          name: angular
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: SPRING_ACTIVEMQ_BROKER-URL
              value: tcp://activemq:61616
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/employeedb
          image: pludynia/simple-web-app:1.5
          name: app
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: liquibase
  name: liquibase
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: liquibase
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: liquibase
    spec:
      containers:
        - args:
            - liquibase
            - update
          env:
            - name: LIQUIBASE_CHANGELOG
              value: dbchangelog.xml
            - name: LIQUIBASE_DATABASE
              value: employeedb
            - name: LIQUIBASE_HOST
              value: postgres
            - name: LIQUIBASE_PASSWORD
              value: Winogrona.2022
            - name: LIQUIBASE_URL
              value: jdbc:postgresql://postgres:5432/employeedb
            - name: LIQUIBASE_USERNAME
              value: postgres
          image: kilna/liquibase-postgres:42.1.4
          name: liquibase
          resources: {}
          volumeMounts:
            - mountPath: /workspace/
              name: liquibase-claim0
      restartPolicy: Always
      volumes:
        - name: liquibase-claim0
          persistentVolumeClaim:
            claimName: liquibase-claim0
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: employeedb
            - name: POSTGRES_PASSWORD
              value: Winogrona.2022
            - name: POSTGRES_USER
              value: postgres
          image: postgres:10.22-alpine
          name: postgres
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
status: {}