version: '3'

services:
  app:
    container_name: application
    image: pludynia/simple-web-app:v2
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/employeedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Winogrona.2022
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    restart: always
    depends_on:
      - activemq
  activemq:
    container_name: activemq
    image: rmohr/activemq:5.15.9-alpine
    restart: always
    environment:
      - SPRING_ACTIVEMQ_BROKER-URL=tcp://postgres:61616
    ports:
      - "61616:61616"
      - "8161:8161"
      - "5672:5672"
  liquibase:
    image: kilna/liquibase-postgres
    container_name: liquibase
    command: liquibase update
    environment:
      - LIQUIBASE_HOST=postgres
      - LIQUIBASE_DATABASE=employeedb
      - LIQUIBASE_USERNAME=postgres
      - LIQUIBASE_PASSWORD=Winogrona.2022
      - LIQUIBASE_CHANGELOG=C:\Users\p.ludynia\IdeaProjects\simpleWebApp\src\main\resources\db\changelog
      - LIQUIBASE_URL=jdbc:postgresql://postgres:5432/employeedb
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:10.22-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=Winogrona.2022
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employeedb
    ports:
      - "5432:5432"



