version: '3'

services:
  app:
    container_name: app
    image: pludynia/simple-web-app:1.5
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/employeedb
      - SPRING_ACTIVEMQ_BROKER-URL=tcp://activemq:61616
    ports:
      - "8080:8080"
    depends_on:
      - activemq
      - postgres

  angular:
    container_name: angular
    image: pludynia/simple-web-app-frontend:1.5
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - postgres
      - activemq
      - app

  activemq:
    container_name: active
    image: rmohr/activemq:5.15.9-alpine
    restart: always
    ports:
      - "61616:61616"
      - "8161:8161"

  liquibase:
    container_name: liquibase
    image: kilna/liquibase-postgres:42.1.4
    command: liquibase update
    environment:
      - LIQUIBASE_HOST=postgres
      - LIQUIBASE_DATABASE=employeedb
      - LIQUIBASE_USERNAME=postgres
      - LIQUIBASE_PASSWORD=Winogrona.2022
      - LIQUIBASE_CHANGELOG=dbchangelog.xml
      - LIQUIBASE_URL=jdbc:postgresql://postgres:5432/employeedb
    depends_on:
      - postgres
    volumes:
      - ./src/main/resources/db/changelog/:/workspace/

  postgres:
    container_name: postgres
    image: postgres:10.22-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=Winogrona.2022
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employeedb
    ports:
      - "5432:5432"




