version: '3'

services:
  app:
    image: pludynia/simple-web-app:v1
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - activemq
      - db
      - liquibase
  liquibase:
    image: liquibase/liquibase:4.7.0
    volumes:
      - ./liquibase:/liquibase/changelog
    command: liquibase --url="jdbc:postgresql://localhost:5432/employeedb" --changeLogFile=./db/changelog/dbchangelog.xml --username=postgres --password=Winogrona.2022 update
    depends_on:
      - db
  activemq:
    image: rmohr/activemq:5.15.9-alpine
    restart: always
    ports:
      - "61616:61616"
      - "8161:8161"
      - "5672:5672"
  db:
    image: postgres:bullseye
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Winogrona.2022
      - POSTGRES_DB=employeedb
    ports:
      - '5432:5432'
