apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: liquibase
  name: liquibase
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: liquibase
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: liquibase
    spec:
      containers:
        - args:
            - liquibase
            - update
          env:
            - name: LIQUIBASE_CHANGELOG
              value: dbchangelog.xml
            - name: LIQUIBASE_DATABASE
              value: employeedb
            - name: LIQUIBASE_HOST
              value: postgres
            - name: LIQUIBASE_PASSWORD
              value: Winogrona.2022
            - name: LIQUIBASE_URL
              value: jdbc:postgresql://postgres:5432/employeedb
            - name: LIQUIBASE_USERNAME
              value: postgres
          image: kilna/liquibase-postgres:42.1.4
          name: liquibase
          resources: {}
          volumeMounts:
            - mountPath: /workspace/
              name: liquibase-claim0
      restartPolicy: Always
      volumes:
        - name: liquibase-claim0
          persistentVolumeClaim:
            claimName: liquibase-claim0
status: {}
